apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: 1

  minReadySeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: dhritishleo/kubenginx:v1

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi

          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10

          livenessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
