apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 2

  minReadySeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: dhritishleo/inventory-server:v1

          ports:
            - containerPort: 5000

          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1

          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret

          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true

      volumes:
        - name: secrets
          secret:
            secretName: firebase-secret
